# -*- coding: utf-8 -*-
"""GT4(mixedSNE).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ofp_ECDC-9raddbaYZQIwwP8MzR218_I
"""

import random

def user_input():
    while True:
        user = input("Enter your choice (rock,paper,scissor): ").lower()
        if user in ["rock","paper","scissor"]:
            return user
        else:
            print("Invalid input")

def winner_tie(player1,player2):

    if player1 == player2:
        return "It's a tie"
    elif player1 == "rock" and player2 == "scissor":
        return "You wins"
    elif player1 == "paper" and player2 == "rock":
        return "You wins"
    elif player1 == "scissor" and player2 =="paper":
        return "you won"
    else:
        return "Computer wins"

def nash_equilibrium():
    print("Nash Equilibrium:\n")
    print("User:")
    for choice in ["rock","paper","scissors"]:
        print(f"Probability of choosing {choice}: 1/3")

    print("\nComputer: ")
    for choice in ["rock","paper","scissors"]:
        print(f"Probability of choosing {choice}: 1/3")


player1 = user_input()
print(f"You choose :'{player1}'")

player2 = random.choice(["rock","paper","scissors"])
print(f"Computer choose: '{player2}'")

result = winner_tie(player1,player2)
print(result)

print()
nash_equilibrium()