# -*- coding: utf-8 -*-
"""GT5(Minmax).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAl9xctA1k231lVS_bfeVZqlQQXAewtz
"""

def minmax_maxmin_saddle(matrix):

    rows,cols = len(matrix) , len(matrix[0])

    minmax_strategy = [min(row) for row in matrix]
    maxmin_strategy = [max(col) for col in zip(*matrix)]   # zip* = takes the transpose of the matrix

    saddle_point = None
    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == minmax_strategy[i] == maxmin_strategy[j]:
                saddle_point = (i,j)
                break
    return minmax_strategy,maxmin_strategy,saddle_point


matrix = [
    [3,2,5],
    [1,4,6],
    [7,8,9]
]

minmax,maxmin,saddle_point = minmax_maxmin_saddle(matrix)
print("Minmax Strategy ",minmax)
print("Maxmin Strategy ",maxmin)
print("Saddle Point",saddle_point)