# -*- coding: utf-8 -*-
"""GT7(social).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105JMg1V69abSt-XPY3qV4uvYckIGKuUQ
"""

def majority_voting(choices):

    counts = {}
    for choice in choices:
        if choice in counts:
            counts[choice] += 1
        else:
            counts[choice] = 1

    max_count = max(counts.values())

    max_choices = [choice for choice, count in counts.items() if count == max_count]

    if len(max_choices) == 1:
        return max_choices[0]
    else:
        return max_choices[0]

individual_choices = ['A','B','C','A','B','A']
social_choice = majority_voting(individual_choices)
print(social_choice)